"""
Seed Lexicon: Initial word-to-concept mappings for bootstrapping the tokenizer.

Each entry maps a word to its conceptual decomposition using the 49 primitives
of the Sistema 7×7. Format: {primitive_name: (state, intensity)}
  state: "+" = active, "0" = zero (active absence), "-" = negative pole (dual principles)
  intensity: 0.0 to 1.0

Three tiers:
  Tier 1: Direct mappings (1 word → 1 primitive)
  Tier 2: Compound mappings (1 word → 2-5 primitives)
  Tier 3: Context-dependent mappings (1 word → multiple possible decompositions)
"""

# ═══════════════════════════════════════════════════════════════════
# TIER 1: Direct mappings (~500 words → 1 primitive each)
# ═══════════════════════════════════════════════════════════════════

TIER_1 = {
    # ─── ELEMENTOS ───
    "fire": {"Fuego": ("+", 0.9)},
    "flame": {"Fuego": ("+", 0.9)},
    "blaze": {"Fuego": ("+", 0.95)},
    "burn": {"Fuego": ("+", 0.8)},
    "heat": {"Fuego": ("+", 0.7)},
    "ember": {"Fuego": ("+", 0.4)},
    "spark": {"Fuego": ("+", 0.5)},
    "earth": {"Tierra": ("+", 0.9)},
    "ground": {"Tierra": ("+", 0.8)},
    "soil": {"Tierra": ("+", 0.85)},
    "dirt": {"Tierra": ("+", 0.7)},
    "rock": {"Tierra": ("+", 0.8)},
    "stone": {"Tierra": ("+", 0.85)},
    "mountain": {"Tierra": ("+", 0.9)},
    "land": {"Tierra": ("+", 0.8)},
    "clay": {"Tierra": ("+", 0.7)},
    "sand": {"Tierra": ("+", 0.6)},
    "water": {"Agua": ("+", 0.9)},
    "river": {"Agua": ("+", 0.8)},
    "ocean": {"Agua": ("+", 0.95)},
    "sea": {"Agua": ("+", 0.9)},
    "lake": {"Agua": ("+", 0.8)},
    "rain": {"Agua": ("+", 0.7)},
    "wave": {"Agua": ("+", 0.7)},
    "stream": {"Agua": ("+", 0.7)},
    "drop": {"Agua": ("+", 0.4)},
    "flood": {"Agua": ("+", 0.95)},
    "ice": {"Agua": ("+", 0.7)},
    "air": {"Aire": ("+", 0.9)},
    "wind": {"Aire": ("+", 0.8)},
    "breeze": {"Aire": ("+", 0.5)},
    "breath": {"Aire": ("+", 0.7)},
    "sky": {"Aire": ("+", 0.8)},
    "storm": {"Aire": ("+", 0.9)},
    "gust": {"Aire": ("+", 0.7)},
    "void": {"Vacío": ("+", 0.9)},
    "emptiness": {"Vacío": ("+", 0.85)},
    "nothing": {"Vacío": ("+", 0.8)},
    "gap": {"Vacío": ("+", 0.6)},
    "hollow": {"Vacío": ("+", 0.7)},
    "blank": {"Vacío": ("+", 0.7)},
    "vacuum": {"Vacío": ("+", 0.9)},
    "absence": {"Vacío": ("+", 0.8)},
    "information": {"Información": ("+", 0.9)},
    "data": {"Información": ("+", 0.8)},
    "code": {"Información": ("+", 0.8)},
    "message": {"Información": ("+", 0.7)},
    "signal": {"Información": ("+", 0.7)},
    "pattern": {"Información": ("+", 0.7)},
    "number": {"Información": ("+", 0.6)},
    "word": {"Información": ("+", 0.7)},
    "symbol": {"Información": ("+", 0.7)},
    "knowledge": {"Información": ("+", 0.8)},
    "force": {"Fuerza": ("+", 0.9)},
    "power": {"Fuerza": ("+", 0.85)},
    "strength": {"Fuerza": ("+", 0.8)},
    "energy": {"Fuerza": ("+", 0.8)},
    "push": {"Fuerza": ("+", 0.6)},
    "pull": {"Fuerza": ("+", 0.6)},
    "pressure": {"Fuerza": ("+", 0.7)},
    "gravity": {"Fuerza": ("+", 0.8)},
    "momentum": {"Fuerza": ("+", 0.7)},

    # ─── CARACTERÍSTICAS ───
    "color": {"Color": ("+", 0.9)},
    "red": {"Color": ("+", 0.8)},
    "blue": {"Color": ("+", 0.8)},
    "green": {"Color": ("+", 0.8)},
    "yellow": {"Color": ("+", 0.8)},
    "white": {"Color": ("+", 0.8)},
    "black": {"Color": ("+", 0.8)},
    "orange": {"Color": ("+", 0.8)},
    "purple": {"Color": ("+", 0.8)},
    "pink": {"Color": ("+", 0.7)},
    "golden": {"Color": ("+", 0.7)},
    "silver": {"Color": ("+", 0.7)},
    "texture": {"Textura": ("+", 0.9)},
    "rough": {"Textura": ("+", 0.7)},
    "smooth": {"Textura": ("+", 0.7)},
    "soft": {"Textura": ("+", 0.7)},
    "coarse": {"Textura": ("+", 0.7)},
    "silky": {"Textura": ("+", 0.7)},
    "shape": {"Forma": ("+", 0.9)},
    "circle": {"Forma": ("+", 0.8)},
    "square": {"Forma": ("+", 0.8)},
    "triangle": {"Forma": ("+", 0.8)},
    "sphere": {"Forma": ("+", 0.8)},
    "curve": {"Forma": ("+", 0.7)},
    "line": {"Forma": ("+", 0.7)},
    "spiral": {"Forma": ("+", 0.7)},
    "material": {"Material": ("+", 0.9)},
    "wood": {"Material": ("+", 0.8)},
    "metal": {"Material": ("+", 0.8)},
    "glass": {"Material": ("+", 0.8)},
    "plastic": {"Material": ("+", 0.7)},
    "fabric": {"Material": ("+", 0.7)},
    "concrete": {"Material": ("+", 0.7)},
    "steel": {"Material": ("+", 0.8)},
    "bright": {"Brillo": ("+", 0.8)},
    "glow": {"Brillo": ("+", 0.7)},
    "shine": {"Brillo": ("+", 0.7)},
    "radiant": {"Brillo": ("+", 0.8)},
    "dazzling": {"Brillo": ("+", 0.9)},
    "dim": {"Brillo": ("+", 0.3)},
    "transparent": {"Transparencia": ("+", 0.8)},
    "opaque": {"Transparencia": ("+", 0.3)},
    "translucent": {"Transparencia": ("+", 0.6)},
    "clear": {"Transparencia": ("+", 0.8)},
    "solid": {"Estado_materia": ("+", 0.8)},
    "liquid": {"Estado_materia": ("+", 0.8)},
    "gas": {"Estado_materia": ("+", 0.8)},
    "frozen": {"Estado_materia": ("+", 0.7)},
    "molten": {"Estado_materia": ("+", 0.7)},

    # ─── ESPACIO ───
    "up": {"Arriba": ("+", 0.8)},
    "above": {"Arriba": ("+", 0.8)},
    "high": {"Arriba": ("+", 0.7)},
    "sky": {"Arriba": ("+", 0.7)},
    "top": {"Arriba": ("+", 0.8)},
    "ceiling": {"Arriba": ("+", 0.7)},
    "down": {"Abajo": ("+", 0.8)},
    "below": {"Abajo": ("+", 0.8)},
    "low": {"Abajo": ("+", 0.7)},
    "bottom": {"Abajo": ("+", 0.8)},
    "floor": {"Abajo": ("+", 0.7)},
    "underground": {"Abajo": ("+", 0.8)},
    "center": {"En_medio": ("+", 0.8)},
    "middle": {"En_medio": ("+", 0.8)},
    "between": {"En_medio": ("+", 0.7)},
    "core": {"En_medio": ("+", 0.7)},
    "forward": {"Adelante": ("+", 0.8)},
    "ahead": {"Adelante": ("+", 0.8)},
    "front": {"Adelante": ("+", 0.7)},
    "backward": {"Atrás": ("+", 0.8)},
    "behind": {"Atrás": ("+", 0.8)},
    "back": {"Atrás": ("+", 0.7)},
    "left": {"Izquierda_Derecha": ("+", 0.7)},
    "right": {"Izquierda_Derecha": ("+", 0.7)},
    "side": {"Izquierda_Derecha": ("+", 0.6)},
    "inside": {"Dentro_Fuera": ("+", 0.8)},
    "within": {"Dentro_Fuera": ("+", 0.8)},
    "interior": {"Dentro_Fuera": ("+", 0.7)},
    "outside": {"Dentro_Fuera": ("+", 0.8)},
    "exterior": {"Dentro_Fuera": ("+", 0.7)},
    "boundary": {"Dentro_Fuera": ("+", 0.7)},
    "edge": {"Dentro_Fuera": ("+", 0.6)},

    # ─── TIEMPO ───
    "now": {"Presente": ("+", 0.9)},
    "today": {"Presente": ("+", 0.8)},
    "current": {"Presente": ("+", 0.7)},
    "here": {"Presente": ("+", 0.7)},
    "moment": {"Presente": ("+", 0.8)},
    "instant": {"Presente": ("+", 0.8)},
    "past": {"Pasado": ("+", 0.9)},
    "yesterday": {"Pasado": ("+", 0.8)},
    "history": {"Pasado": ("+", 0.8)},
    "ago": {"Pasado": ("+", 0.7)},
    "ancient": {"Pasado": ("+", 0.8)},
    "old": {"Pasado": ("+", 0.6)},
    "former": {"Pasado": ("+", 0.6)},
    "future": {"Futuro": ("+", 0.9)},
    "tomorrow": {"Futuro": ("+", 0.8)},
    "next": {"Futuro": ("+", 0.6)},
    "soon": {"Futuro": ("+", 0.6)},
    "eventually": {"Futuro": ("+", 0.5)},
    "destiny": {"Futuro": ("+", 0.8)},
    "pause": {"Pausa": ("+", 0.8)},
    "stop": {"Pausa": ("+", 0.8)},
    "freeze": {"Pausa": ("+", 0.8)},
    "still": {"Pausa": ("+", 0.7)},
    "wait": {"Pausa": ("+", 0.6)},
    "halt": {"Pausa": ("+", 0.8)},
    "remember": {"Ir_al_pasado": ("+", 0.8)},
    "recall": {"Ir_al_pasado": ("+", 0.7)},
    "reminisce": {"Ir_al_pasado": ("+", 0.8)},
    "flashback": {"Ir_al_pasado": ("+", 0.9)},
    "imagine": {"Ir_al_futuro": ("+", 0.8)},
    "anticipate": {"Ir_al_futuro": ("+", 0.7)},
    "predict": {"Ir_al_futuro": ("+", 0.7)},
    "foresee": {"Ir_al_futuro": ("+", 0.8)},
    "envision": {"Ir_al_futuro": ("+", 0.8)},
    "happening": {"Play": ("+", 0.8)},
    "flowing": {"Play": ("+", 0.7)},
    "ongoing": {"Play": ("+", 0.7)},
    "moving": {"Play": ("+", 0.7)},
    "running": {"Play": ("+", 0.7)},
    "alive": {"Play": ("+", 0.7)},

    # ─── SENTIDOS ───
    "see": {"Vista": ("+", 0.8)},
    "look": {"Vista": ("+", 0.7)},
    "watch": {"Vista": ("+", 0.7)},
    "gaze": {"Vista": ("+", 0.7)},
    "stare": {"Vista": ("+", 0.8)},
    "vision": {"Vista": ("+", 0.8)},
    "sight": {"Vista": ("+", 0.8)},
    "glimpse": {"Vista": ("+", 0.5)},
    "hear": {"Oído": ("+", 0.8)},
    "listen": {"Oído": ("+", 0.8)},
    "sound": {"Oído": ("+", 0.8)},
    "noise": {"Oído": ("+", 0.7)},
    "loud": {"Oído": ("+", 0.8)},
    "quiet": {"Oído": ("+", 0.3)},
    "echo": {"Oído": ("+", 0.6)},
    "touch": {"Tacto": ("+", 0.8)},
    "feel": {"Tacto": ("+", 0.7)},
    "grab": {"Tacto": ("+", 0.7)},
    "hold": {"Tacto": ("+", 0.7)},
    "stroke": {"Tacto": ("+", 0.6)},
    "press": {"Tacto": ("+", 0.7)},
    "taste": {"Gusto": ("+", 0.8)},
    "flavor": {"Gusto": ("+", 0.8)},
    "sweet": {"Gusto": ("+", 0.7)},
    "bitter": {"Gusto": ("+", 0.7)},
    "sour": {"Gusto": ("+", 0.7)},
    "salty": {"Gusto": ("+", 0.7)},
    "delicious": {"Gusto": ("+", 0.8)},
    "smell": {"Olfato": ("+", 0.8)},
    "scent": {"Olfato": ("+", 0.7)},
    "aroma": {"Olfato": ("+", 0.7)},
    "fragrance": {"Olfato": ("+", 0.7)},
    "stink": {"Olfato": ("+", 0.7)},
    "odor": {"Olfato": ("+", 0.7)},
    "balance": {"Equilibrio": ("+", 0.8)},
    "dizzy": {"Equilibrio": ("+", 0.7)},
    "steady": {"Equilibrio": ("+", 0.7)},
    "stable": {"Equilibrio": ("+", 0.7)},
    "vertigo": {"Equilibrio": ("+", 0.8)},
    "hunger": {"Interocepción": ("+", 0.7)},
    "thirst": {"Interocepción": ("+", 0.7)},
    "pain": {"Interocepción": ("+", 0.8)},
    "heartbeat": {"Interocepción": ("+", 0.7)},
    "nausea": {"Interocepción": ("+", 0.7)},
    "fatigue": {"Interocepción": ("+", 0.7)},
    "ache": {"Interocepción": ("+", 0.6)},

    # ─── PRINCIPIOS DUALES (polos directos) ───
    "good": {"Bien_Mal": ("+", 0.8)},
    "kind": {"Bien_Mal": ("+", 0.7)},
    "generous": {"Bien_Mal": ("+", 0.7)},
    "noble": {"Bien_Mal": ("+", 0.7)},
    "virtuous": {"Bien_Mal": ("+", 0.8)},
    "evil": {"Bien_Mal": ("-", 0.8)},
    "wicked": {"Bien_Mal": ("-", 0.8)},
    "cruel": {"Bien_Mal": ("-", 0.8)},
    "malicious": {"Bien_Mal": ("-", 0.8)},
    "order": {"Orden_Caos": ("+", 0.8)},
    "organize": {"Orden_Caos": ("+", 0.7)},
    "structure": {"Orden_Caos": ("+", 0.7)},
    "system": {"Orden_Caos": ("+", 0.7)},
    "rule": {"Orden_Caos": ("+", 0.7)},
    "chaos": {"Orden_Caos": ("-", 0.8)},
    "disorder": {"Orden_Caos": ("-", 0.7)},
    "mess": {"Orden_Caos": ("-", 0.6)},
    "random": {"Orden_Caos": ("-", 0.6)},
    "create": {"Creación_Destrucción": ("+", 0.8)},
    "build": {"Creación_Destrucción": ("+", 0.7)},
    "make": {"Creación_Destrucción": ("+", 0.6)},
    "invent": {"Creación_Destrucción": ("+", 0.8)},
    "birth": {"Creación_Destrucción": ("+", 0.8)},
    "grow": {"Creación_Destrucción": ("+", 0.6)},
    "destroy": {"Creación_Destrucción": ("-", 0.8)},
    "break": {"Creación_Destrucción": ("-", 0.7)},
    "ruin": {"Creación_Destrucción": ("-", 0.8)},
    "demolish": {"Creación_Destrucción": ("-", 0.8)},
    "collapse": {"Creación_Destrucción": ("-", 0.7)},
    "unite": {"Unión_Separación": ("+", 0.8)},
    "join": {"Unión_Separación": ("+", 0.7)},
    "connect": {"Unión_Separación": ("+", 0.7)},
    "merge": {"Unión_Separación": ("+", 0.7)},
    "bond": {"Unión_Separación": ("+", 0.7)},
    "together": {"Unión_Separación": ("+", 0.7)},
    "separate": {"Unión_Separación": ("-", 0.8)},
    "divide": {"Unión_Separación": ("-", 0.7)},
    "split": {"Unión_Separación": ("-", 0.7)},
    "apart": {"Unión_Separación": ("-", 0.7)},
    "alone": {"Unión_Separación": ("-", 0.7)},
    "isolate": {"Unión_Separación": ("-", 0.7)},
    "truth": {"Verdad_Mentira": ("+", 0.8)},
    "true": {"Verdad_Mentira": ("+", 0.8)},
    "honest": {"Verdad_Mentira": ("+", 0.7)},
    "authentic": {"Verdad_Mentira": ("+", 0.7)},
    "genuine": {"Verdad_Mentira": ("+", 0.7)},
    "real": {"Verdad_Mentira": ("+", 0.7)},
    "lie": {"Verdad_Mentira": ("-", 0.8)},
    "false": {"Verdad_Mentira": ("-", 0.8)},
    "fake": {"Verdad_Mentira": ("-", 0.7)},
    "deceive": {"Verdad_Mentira": ("-", 0.8)},
    "pretend": {"Verdad_Mentira": ("-", 0.6)},
    "freedom": {"Libertad_Control": ("+", 0.8)},
    "free": {"Libertad_Control": ("+", 0.8)},
    "liberty": {"Libertad_Control": ("+", 0.8)},
    "autonomous": {"Libertad_Control": ("+", 0.7)},
    "release": {"Libertad_Control": ("+", 0.7)},
    "control": {"Libertad_Control": ("-", 0.8)},
    "restrict": {"Libertad_Control": ("-", 0.7)},
    "cage": {"Libertad_Control": ("-", 0.7)},
    "trap": {"Libertad_Control": ("-", 0.7)},
    "chain": {"Libertad_Control": ("-", 0.7)},
    "prison": {"Libertad_Control": ("-", 0.8)},
    "life": {"Vida_Muerte": ("+", 0.8)},
    "living": {"Vida_Muerte": ("+", 0.7)},
    "vitality": {"Vida_Muerte": ("+", 0.8)},
    "thrive": {"Vida_Muerte": ("+", 0.7)},
    "death": {"Vida_Muerte": ("-", 0.8)},
    "dead": {"Vida_Muerte": ("-", 0.8)},
    "dying": {"Vida_Muerte": ("-", 0.7)},
    "kill": {"Vida_Muerte": ("-", 0.8)},
    "extinct": {"Vida_Muerte": ("-", 0.8)},

    # ─── OBSERVADORES ───
    "aware": {"Consciente": ("+", 0.8)},
    "conscious": {"Consciente": ("+", 0.8)},
    "awake": {"Consciente": ("+", 0.7)},
    "mindful": {"Consciente": ("+", 0.7)},
    "realize": {"Consciente": ("+", 0.7)},
    "understand": {"Consciente": ("+", 0.7)},
    "temporary": {"Temporal": ("+", 0.7)},
    "brief": {"Temporal": ("+", 0.7)},
    "fleeting": {"Temporal": ("+", 0.8)},
    "transient": {"Temporal": ("+", 0.7)},
    "eternal": {"Eterno": ("+", 0.8)},
    "forever": {"Eterno": ("+", 0.8)},
    "infinite": {"Eterno": ("+", 0.8)},
    "timeless": {"Eterno": ("+", 0.8)},
    "everlasting": {"Eterno": ("+", 0.8)},
    "personal": {"Individual": ("+", 0.7)},
    "self": {"Individual": ("+", 0.8)},
    "me": {"Individual": ("+", 0.7)},
    "my": {"Individual": ("+", 0.7)},
    "mine": {"Individual": ("+", 0.7)},
    "community": {"Colectivo": ("+", 0.8)},
    "society": {"Colectivo": ("+", 0.8)},
    "group": {"Colectivo": ("+", 0.7)},
    "team": {"Colectivo": ("+", 0.7)},
    "we": {"Colectivo": ("+", 0.7)},
    "our": {"Colectivo": ("+", 0.7)},
    "people": {"Colectivo": ("+", 0.7)},
    "everyone": {"Colectivo": ("+", 0.7)},
    "nobody": {"Ausente": ("+", 0.7)},
    "gone": {"Ausente": ("+", 0.7)},
    "vanished": {"Ausente": ("+", 0.8)},
    "invisible": {"Ausente": ("+", 0.7)},
    "artist": {"Creador": ("+", 0.7)},
    "creator": {"Creador": ("+", 0.8)},
    "maker": {"Creador": ("+", 0.7)},
    "inventor": {"Creador": ("+", 0.8)},
    "architect": {"Creador": ("+", 0.8)},
    "designer": {"Creador": ("+", 0.7)},
    "author": {"Creador": ("+", 0.7)},

    # ─── ESTADOS CERO (ausencias activas) ───
    "silence": {"Oído": ("0", 0.8)},
    "darkness": {"Color": ("0", 0.8)},
    "stillness": {"Play": ("0", 0.8)},
    "numbness": {"Tacto": ("0", 0.7)},
    "blindness": {"Vista": ("0", 0.8)},
    "deafness": {"Oído": ("0", 0.8)},
    "tasteless": {"Gusto": ("0", 0.7)},
    "odorless": {"Olfato": ("0", 0.7)},
    "weightless": {"Equilibrio": ("0", 0.7)},
    "colorless": {"Color": ("0", 0.8)},
}

# ═══════════════════════════════════════════════════════════════════
# TIER 2: Compound mappings (~500 words → 2-5 primitives)
# ═══════════════════════════════════════════════════════════════════

TIER_2 = {
    # ─── EMOCIONES ───
    "love": {"Unión_Separación": ("+", 0.9), "Interocepción": ("+", 0.8), "Consciente": ("+", 0.7), "Bien_Mal": ("+", 0.7), "Vida_Muerte": ("+", 0.6)},
    "hate": {"Unión_Separación": ("-", 0.9), "Interocepción": ("+", 0.8), "Bien_Mal": ("-", 0.7), "Creación_Destrucción": ("-", 0.6)},
    "joy": {"Bien_Mal": ("+", 0.8), "Interocepción": ("+", 0.8), "Vida_Muerte": ("+", 0.6), "Play": ("+", 0.6)},
    "sadness": {"Unión_Separación": ("-", 0.6), "Interocepción": ("+", 0.7), "Individual": ("+", 0.6)},
    "anger": {"Fuerza": ("+", 0.8), "Interocepción": ("+", 0.9), "Bien_Mal": ("-", 0.6), "Creación_Destrucción": ("-", 0.7)},
    "fear": {"Interocepción": ("+", 0.9), "Vida_Muerte": ("-", 0.7), "Futuro": ("+", 0.5), "Individual": ("+", 0.6)},
    "hope": {"Futuro": ("+", 0.7), "Bien_Mal": ("+", 0.6), "Ir_al_futuro": ("+", 0.6), "Vida_Muerte": ("+", 0.5)},
    "despair": {"Futuro": ("0", 0.7), "Bien_Mal": ("-", 0.7), "Interocepción": ("+", 0.8), "Vacío": ("+", 0.6)},
    "nostalgia": {"Ir_al_pasado": ("+", 0.8), "Interocepción": ("+", 0.7), "Unión_Separación": ("-", 0.6), "Bien_Mal": ("+", 0.4)},
    "grief": {"Unión_Separación": ("-", 0.9), "Vida_Muerte": ("-", 0.8), "Interocepción": ("+", 0.9), "Ir_al_pasado": ("+", 0.6)},
    "pride": {"Bien_Mal": ("+", 0.6), "Individual": ("+", 0.8), "Arriba": ("+", 0.5), "Consciente": ("+", 0.6)},
    "shame": {"Bien_Mal": ("-", 0.7), "Individual": ("+", 0.8), "Interocepción": ("+", 0.7), "Abajo": ("+", 0.5)},
    "loneliness": {"Individual": ("+", 0.8), "Colectivo": ("0", 0.7), "Interocepción": ("+", 0.7), "Unión_Separación": ("-", 0.7)},
    "peace": {"Orden_Caos": ("+", 0.7), "Interocepción": ("+", 0.5), "Pausa": ("+", 0.5), "Bien_Mal": ("+", 0.5)},
    "anxiety": {"Futuro": ("+", 0.7), "Interocepción": ("+", 0.8), "Orden_Caos": ("-", 0.6), "Libertad_Control": ("-", 0.5)},
    "curiosity": {"Ir_al_futuro": ("+", 0.7), "Consciente": ("+", 0.7), "Verdad_Mentira": ("+", 0.5), "Vacío": ("+", 0.4)},
    "boredom": {"Información": ("0", 0.7), "Creación_Destrucción": ("0", 0.6), "Interocepción": ("+", 0.5), "Presente": ("+", 0.6)},
    "awe": {"Arriba": ("+", 0.6), "Eterno": ("+", 0.5), "Interocepción": ("+", 0.8), "Consciente": ("+", 0.7)},
    "jealousy": {"Unión_Separación": ("-", 0.7), "Individual": ("+", 0.8), "Bien_Mal": ("-", 0.5), "Interocepción": ("+", 0.7)},
    "gratitude": {"Unión_Separación": ("+", 0.7), "Bien_Mal": ("+", 0.7), "Consciente": ("+", 0.6), "Interocepción": ("+", 0.5)},
    "compassion": {"Unión_Separación": ("+", 0.7), "Bien_Mal": ("+", 0.7), "Individual": ("+", 0.5), "Colectivo": ("+", 0.5)},
    "excitement": {"Fuerza": ("+", 0.7), "Play": ("+", 0.7), "Interocepción": ("+", 0.7), "Futuro": ("+", 0.5)},
    "calm": {"Pausa": ("+", 0.5), "Equilibrio": ("+", 0.7), "Orden_Caos": ("+", 0.5), "Interocepción": ("+", 0.4)},
    "rage": {"Fuerza": ("+", 0.95), "Interocepción": ("+", 0.95), "Creación_Destrucción": ("-", 0.9), "Orden_Caos": ("-", 0.7)},
    "melancholy": {"Unión_Separación": ("-", 0.5), "Pasado": ("+", 0.6), "Consciente": ("+", 0.6), "Interocepción": ("+", 0.5)},

    # ─── FENÓMENOS NATURALES ───
    "sunrise": {"Fuego": ("+", 0.7), "Arriba": ("+", 0.7), "Color": ("+", 0.8), "Brillo": ("+", 0.8), "Presente": ("+", 0.6)},
    "sunset": {"Fuego": ("+", 0.5), "Abajo": ("+", 0.6), "Color": ("+", 0.8), "Brillo": ("+", 0.5), "Pasado": ("+", 0.5)},
    "lightning": {"Fuego": ("+", 0.8), "Fuerza": ("+", 0.9), "Brillo": ("+", 0.9), "Aire": ("+", 0.6)},
    "thunder": {"Oído": ("+", 0.9), "Fuerza": ("+", 0.8), "Aire": ("+", 0.6)},
    "earthquake": {"Tierra": ("+", 0.9), "Fuerza": ("+", 0.9), "Creación_Destrucción": ("-", 0.7), "Abajo": ("+", 0.7)},
    "rainbow": {"Color": ("+", 0.9), "Agua": ("+", 0.5), "Arriba": ("+", 0.6), "Brillo": ("+", 0.7), "Vista": ("+", 0.7)},
    "volcano": {"Fuego": ("+", 0.9), "Tierra": ("+", 0.8), "Fuerza": ("+", 0.9), "Creación_Destrucción": ("-", 0.8)},
    "snow": {"Agua": ("+", 0.7), "Color": ("+", 0.5), "Abajo": ("+", 0.5), "Pausa": ("+", 0.4)},
    "fog": {"Aire": ("+", 0.6), "Agua": ("+", 0.4), "Vista": ("0", 0.5), "Transparencia": ("+", 0.3)},
    "shadow": {"Brillo": ("0", 0.7), "Vista": ("+", 0.6), "Vacío": ("+", 0.5)},
    "night": {"Brillo": ("0", 0.8), "Color": ("0", 0.6), "Pausa": ("+", 0.5)},

    # ─── PERSONAS Y ROLES ───
    "king": {"Tierra": ("+", 0.5), "Fuerza": ("+", 0.7), "Orden_Caos": ("+", 0.7), "Individual": ("+", 0.7), "Consciente": ("+", 0.6)},
    "queen": {"Tierra": ("+", 0.5), "Fuerza": ("+", 0.7), "Orden_Caos": ("+", 0.7), "Individual": ("+", 0.7), "Consciente": ("+", 0.6)},
    "child": {"Vida_Muerte": ("+", 0.7), "Creación_Destrucción": ("+", 0.5), "Individual": ("+", 0.6), "Temporal": ("+", 0.6)},
    "mother": {"Vida_Muerte": ("+", 0.7), "Creación_Destrucción": ("+", 0.7), "Unión_Separación": ("+", 0.7), "Individual": ("+", 0.6)},
    "father": {"Vida_Muerte": ("+", 0.7), "Creación_Destrucción": ("+", 0.6), "Fuerza": ("+", 0.5), "Individual": ("+", 0.6)},
    "warrior": {"Fuerza": ("+", 0.8), "Creación_Destrucción": ("-", 0.6), "Vida_Muerte": ("+", 0.6), "Individual": ("+", 0.7)},
    "teacher": {"Información": ("+", 0.7), "Consciente": ("+", 0.7), "Unión_Separación": ("+", 0.5), "Creador": ("+", 0.5)},
    "healer": {"Vida_Muerte": ("+", 0.8), "Bien_Mal": ("+", 0.7), "Tacto": ("+", 0.5), "Creación_Destrucción": ("+", 0.6)},
    "thief": {"Libertad_Control": ("+", 0.5), "Verdad_Mentira": ("-", 0.7), "Bien_Mal": ("-", 0.5), "Individual": ("+", 0.7)},
    "hero": {"Bien_Mal": ("+", 0.8), "Fuerza": ("+", 0.7), "Creación_Destrucción": ("+", 0.5), "Consciente": ("+", 0.7), "Creador": ("+", 0.6)},
    "villain": {"Bien_Mal": ("-", 0.8), "Fuerza": ("+", 0.7), "Libertad_Control": ("-", 0.7), "Individual": ("+", 0.8)},

    # ─── ACCIONES COMPUESTAS ───
    "sing": {"Oído": ("+", 0.8), "Aire": ("+", 0.6), "Creación_Destrucción": ("+", 0.5), "Play": ("+", 0.6)},
    "dance": {"Tacto": ("+", 0.5), "Equilibrio": ("+", 0.7), "Play": ("+", 0.7), "Forma": ("+", 0.5)},
    "dream": {"Vista": ("+", 0.5), "Consciente": ("+", 0.4), "Ir_al_futuro": ("+", 0.5), "Verdad_Mentira": ("-", 0.3)},
    "fight": {"Fuerza": ("+", 0.8), "Unión_Separación": ("-", 0.7), "Creación_Destrucción": ("-", 0.6), "Presente": ("+", 0.7)},
    "pray": {"Arriba": ("+", 0.5), "Consciente": ("+", 0.7), "Eterno": ("+", 0.5), "Interocepción": ("+", 0.5)},
    "fly": {"Aire": ("+", 0.8), "Arriba": ("+", 0.7), "Libertad_Control": ("+", 0.7), "Fuerza": ("+", 0.5)},
    "fall": {"Abajo": ("+", 0.8), "Fuerza": ("+", 0.6), "Creación_Destrucción": ("-", 0.4)},
    "sleep": {"Consciente": ("0", 0.7), "Pausa": ("+", 0.6), "Interocepción": ("+", 0.4)},
    "wake": {"Consciente": ("+", 0.8), "Play": ("+", 0.7), "Presente": ("+", 0.6)},
    "explore": {"Adelante": ("+", 0.6), "Consciente": ("+", 0.7), "Ir_al_futuro": ("+", 0.5), "Vacío": ("+", 0.4)},
    "hide": {"Dentro_Fuera": ("+", 0.7), "Ausente": ("+", 0.6), "Verdad_Mentira": ("-", 0.4)},
    "reveal": {"Verdad_Mentira": ("+", 0.8), "Dentro_Fuera": ("+", 0.6), "Vista": ("+", 0.5), "Consciente": ("+", 0.5)},
    "transform": {"Creación_Destrucción": ("+", 0.7), "Creación_Destrucción": ("-", 0.5), "Fuerza": ("+", 0.6), "Play": ("+", 0.5)},
    "meditate": {"Consciente": ("+", 0.8), "Pausa": ("+", 0.7), "Dentro_Fuera": ("+", 0.5), "Interocepción": ("+", 0.7)},
    "write": {"Información": ("+", 0.7), "Creador": ("+", 0.7), "Forma": ("+", 0.5), "Consciente": ("+", 0.6)},
    "read": {"Vista": ("+", 0.7), "Información": ("+", 0.7), "Consciente": ("+", 0.6)},
    "teach": {"Información": ("+", 0.7), "Unión_Separación": ("+", 0.6), "Consciente": ("+", 0.6), "Creador": ("+", 0.5)},
    "learn": {"Información": ("+", 0.7), "Consciente": ("+", 0.7), "Creación_Destrucción": ("+", 0.4)},

    # ─── CONCEPTOS ABSTRACTOS ───
    "music": {"Aire": ("+", 0.5), "Oído": ("+", 0.9), "Play": ("+", 0.7), "Orden_Caos": ("+", 0.5), "Fuerza": ("+", 0.4)},
    "beauty": {"Vista": ("+", 0.6), "Orden_Caos": ("+", 0.5), "Bien_Mal": ("+", 0.5), "Consciente": ("+", 0.6)},
    "justice": {"Orden_Caos": ("+", 0.7), "Bien_Mal": ("+", 0.7), "Verdad_Mentira": ("+", 0.6), "Colectivo": ("+", 0.6)},
    "wisdom": {"Consciente": ("+", 0.8), "Eterno": ("+", 0.5), "Información": ("+", 0.6), "Verdad_Mentira": ("+", 0.6)},
    "courage": {"Fuerza": ("+", 0.7), "Vida_Muerte": ("+", 0.6), "Bien_Mal": ("+", 0.6), "Consciente": ("+", 0.6)},
    "war": {"Fuerza": ("+", 0.9), "Creación_Destrucción": ("-", 0.8), "Unión_Separación": ("-", 0.7), "Colectivo": ("+", 0.7)},
    "memory": {"Ir_al_pasado": ("+", 0.8), "Consciente": ("+", 0.7), "Información": ("+", 0.5)},
    "time": {"Presente": ("+", 0.5), "Pasado": ("+", 0.5), "Futuro": ("+", 0.5), "Play": ("+", 0.6)},
    "space": {"Arriba": ("+", 0.3), "Abajo": ("+", 0.3), "Adelante": ("+", 0.3), "Dentro_Fuera": ("+", 0.3)},
    "home": {"Dentro_Fuera": ("+", 0.7), "Tierra": ("+", 0.6), "Unión_Separación": ("+", 0.6), "Orden_Caos": ("+", 0.5)},
    "journey": {"Adelante": ("+", 0.7), "Play": ("+", 0.6), "Creación_Destrucción": ("+", 0.4), "Consciente": ("+", 0.5)},
    "treasure": {"Bien_Mal": ("+", 0.6), "Material": ("+", 0.6), "Brillo": ("+", 0.5), "Dentro_Fuera": ("+", 0.5)},
    "gift": {"Unión_Separación": ("+", 0.7), "Bien_Mal": ("+", 0.6), "Creación_Destrucción": ("+", 0.4)},
    "sacrifice": {"Creación_Destrucción": ("-", 0.6), "Bien_Mal": ("+", 0.7), "Individual": ("+", 0.6), "Colectivo": ("+", 0.5)},
    "revenge": {"Creación_Destrucción": ("-", 0.7), "Bien_Mal": ("-", 0.5), "Ir_al_pasado": ("+", 0.6), "Fuerza": ("+", 0.6)},
    "forgiveness": {"Unión_Separación": ("+", 0.7), "Bien_Mal": ("+", 0.7), "Libertad_Control": ("+", 0.5), "Consciente": ("+", 0.6)},

    # ─── OBJETOS COMPUESTOS ───
    "sword": {"Fuerza": ("+", 0.7), "Material": ("+", 0.7), "Forma": ("+", 0.6), "Creación_Destrucción": ("-", 0.5)},
    "book": {"Información": ("+", 0.8), "Material": ("+", 0.5), "Vista": ("+", 0.5), "Consciente": ("+", 0.5)},
    "mirror": {"Vista": ("+", 0.7), "Brillo": ("+", 0.6), "Transparencia": ("+", 0.6), "Verdad_Mentira": ("+", 0.4)},
    "candle": {"Fuego": ("+", 0.6), "Brillo": ("+", 0.6), "Color": ("+", 0.5), "Pausa": ("+", 0.3)},
    "door": {"Dentro_Fuera": ("+", 0.8), "Forma": ("+", 0.5), "Material": ("+", 0.5), "Libertad_Control": ("+", 0.4)},
    "bridge": {"Unión_Separación": ("+", 0.7), "Forma": ("+", 0.6), "Material": ("+", 0.6), "Arriba": ("+", 0.4)},
    "crown": {"Fuerza": ("+", 0.6), "Material": ("+", 0.5), "Arriba": ("+", 0.6), "Orden_Caos": ("+", 0.5)},
    "tree": {"Vida_Muerte": ("+", 0.7), "Tierra": ("+", 0.6), "Arriba": ("+", 0.6), "Creación_Destrucción": ("+", 0.5)},
    "star": {"Fuego": ("+", 0.7), "Brillo": ("+", 0.9), "Arriba": ("+", 0.8), "Eterno": ("+", 0.5)},
    "moon": {"Brillo": ("+", 0.6), "Arriba": ("+", 0.7), "Pausa": ("+", 0.4), "Eterno": ("+", 0.5)},
    "sun": {"Fuego": ("+", 0.8), "Brillo": ("+", 0.9), "Arriba": ("+", 0.8), "Vida_Muerte": ("+", 0.6)},
    "river": {"Agua": ("+", 0.8), "Play": ("+", 0.6), "Adelante": ("+", 0.5), "Forma": ("+", 0.4)},
    "forest": {"Vida_Muerte": ("+", 0.7), "Tierra": ("+", 0.6), "Dentro_Fuera": ("+", 0.5), "Colectivo": ("+", 0.4)},
    "castle": {"Tierra": ("+", 0.7), "Material": ("+", 0.7), "Forma": ("+", 0.6), "Dentro_Fuera": ("+", 0.6), "Fuerza": ("+", 0.5)},
}

# ═══════════════════════════════════════════════════════════════════
# TIER 3: Context-dependent mappings (multiple possible decompositions)
# ═══════════════════════════════════════════════════════════════════

TIER_3 = {
    "bank": [
        {"Tierra": ("+", 0.7), "Agua": ("+", 0.5), "Forma": ("+", 0.4)},
        {"Información": ("+", 0.7), "Orden_Caos": ("+", 0.6), "Libertad_Control": ("-", 0.5)},
    ],
    "spring": [
        {"Agua": ("+", 0.7), "Tierra": ("+", 0.4), "Arriba": ("+", 0.4)},
        {"Vida_Muerte": ("+", 0.7), "Creación_Destrucción": ("+", 0.6), "Play": ("+", 0.5)},
        {"Fuerza": ("+", 0.7), "Forma": ("+", 0.5)},
    ],
    "light": [
        {"Brillo": ("+", 0.8), "Vista": ("+", 0.6)},
        {"Fuerza": ("+", 0.3)},
    ],
    "run": [
        {"Fuerza": ("+", 0.6), "Adelante": ("+", 0.6), "Play": ("+", 0.7)},
        {"Play": ("+", 0.7)},
    ],
    "hard": [
        {"Material": ("+", 0.7), "Textura": ("+", 0.7)},
        {"Fuerza": ("+", 0.6)},
    ],
    "cold": [
        {"Fuego": ("0", 0.7), "Tacto": ("+", 0.6)},
        {"Unión_Separación": ("-", 0.5), "Interocepción": ("+", 0.4)},
    ],
    "warm": [
        {"Fuego": ("+", 0.5), "Tacto": ("+", 0.6)},
        {"Unión_Separación": ("+", 0.5), "Bien_Mal": ("+", 0.4)},
    ],
    "deep": [
        {"Abajo": ("+", 0.7), "Dentro_Fuera": ("+", 0.5)},
        {"Consciente": ("+", 0.6), "Verdad_Mentira": ("+", 0.5)},
    ],
    "sharp": [
        {"Forma": ("+", 0.7), "Fuerza": ("+", 0.5)},
        {"Consciente": ("+", 0.7), "Vista": ("+", 0.5)},
    ],
    "bright": [
        {"Brillo": ("+", 0.8), "Vista": ("+", 0.6)},
        {"Consciente": ("+", 0.7), "Información": ("+", 0.5)},
    ],
    "dark": [
        {"Brillo": ("0", 0.7), "Color": ("0", 0.6)},
        {"Bien_Mal": ("-", 0.6), "Verdad_Mentira": ("-", 0.4)},
    ],
    "heavy": [
        {"Fuerza": ("+", 0.7), "Abajo": ("+", 0.5), "Material": ("+", 0.5)},
        {"Interocepción": ("+", 0.7), "Unión_Separación": ("-", 0.5)},
    ],
    "rise": [
        {"Arriba": ("+", 0.8), "Fuerza": ("+", 0.5), "Play": ("+", 0.5)},
        {"Creación_Destrucción": ("+", 0.6), "Fuerza": ("+", 0.5)},
    ],
    "fall": [
        {"Abajo": ("+", 0.8), "Fuerza": ("+", 0.6)},
        {"Creación_Destrucción": ("-", 0.6)},
    ],
    "open": [
        {"Dentro_Fuera": ("+", 0.7), "Libertad_Control": ("+", 0.5)},
        {"Verdad_Mentira": ("+", 0.5), "Consciente": ("+", 0.4)},
    ],
    "close": [
        {"Dentro_Fuera": ("+", 0.7), "Libertad_Control": ("-", 0.5)},
        {"Unión_Separación": ("+", 0.5)},
    ],
    "play": [
        {"Play": ("+", 0.8), "Libertad_Control": ("+", 0.5), "Creación_Destrucción": ("+", 0.4)},
        {"Play": ("+", 0.7)},
    ],
    "rest": [
        {"Pausa": ("+", 0.7), "Equilibrio": ("+", 0.5), "Interocepción": ("+", 0.4)},
        {"Vida_Muerte": ("-", 0.3), "Pausa": ("+", 0.7)},
    ],
}

# ═══════════════════════════════════════════════════════════════════
# Combined lexicon
# ═══════════════════════════════════════════════════════════════════

def get_full_lexicon() -> dict:
    """Return the complete lexicon (Tier 1 + Tier 2 merged, Tier 3 separate)."""
    lexicon = {}
    lexicon.update(TIER_1)
    lexicon.update(TIER_2)
    return lexicon


def get_ambiguous_lexicon() -> dict:
    """Return only Tier 3 (context-dependent words)."""
    return TIER_3.copy()


def lexicon_stats() -> dict:
    """Return statistics about the lexicon."""
    all_primitives_used = set()
    for entry in TIER_1.values():
        all_primitives_used.update(entry.keys())
    for entry in TIER_2.values():
        all_primitives_used.update(entry.keys())
    for entries in TIER_3.values():
        for entry in entries:
            all_primitives_used.update(entry.keys())

    return {
        "tier_1_count": len(TIER_1),
        "tier_2_count": len(TIER_2),
        "tier_3_count": len(TIER_3),
        "total_unambiguous": len(TIER_1) + len(TIER_2),
        "total_words": len(TIER_1) + len(TIER_2) + len(TIER_3),
        "primitives_used": len(all_primitives_used),
        "primitives_unused": 49 - len(all_primitives_used),
    }
